### ISSUE TITLE
one-wire-on-fire.org is down

### ISSUE THREAD

**Issue by frederickjh** [lancemiller/One-Wire-On-Fire#1]
Hi Lance!

I am trying to setup the one-wire-on-fire program but am not succeeding. The website is down so I hunted around and found this github repo. I cloned it but even after moving the special file _ONE-WIRE-ON-FIRE_py.txt to  a directory in the path at /usr/local/bin and making it executable I get this when I try and run it on the command line:

<pre>
/usr/local/bin$ ls -l
total 232
-rwxr-xr-x 1 root root   1799 2010-11-21 22:14 add_new_sensor.sh
-rwxr-xr-x 1 root root  13650 2015-02-21 23:34 OneWireOnFire.py
-rwxr-xr-x 1 root root  81713 2010-11-21 22:14 rrd_replace
-rwxr-xr-x 1 root root 134233 2010-11-21 22:14 temploggerd
fhenderson@ubuntuserver:/usr/local/bin$ OneWireOnFire.py 
  File "/usr/local/bin/OneWireOnFire.py", line 2
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
/usr/local/bin$ 
</pre>

I tried this as I get a white screen when I visit http://localhost/One-Wire-On-Fire in web browser. View page source shows no text.

Any help you can give me in getting this working would be appreciated.

Thanks for your time and help!

Frederick

**Comment by lancemiller** [comment]
For me http://one-wire-on-fire.org/ is up.

**Comment by frederickjh** [comment]
Hi Lance!

Here in Switzerland it is still does not load. Trying to connect to it never loads a page and the connection times out. The same happens for http://reliablewebs.com/

I wondered if there is either blocking based on ip address or Bogon filtering(http://en.wikipedia.org/wiki/Bogon_filtering) going on.  So, I hooked up to a free vpn that made it look like I was coming from Chicago. Through the vpn I can access the site.

Maybe something to ask you Hosting provider about. DNS lookup gives the ip address of 74.119.146.162 for one-wire-on-fire-.org

Thanks again for your time, help and one-wire-on-fire!

Frederick
